---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-example-deployment
  namespace: gitops-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-example-app
  template:
    metadata:
      labels:
        app: gitops-example-app
    spec:
      containers:
        - name: gitops-example-container
          # This is the line that gets update automatically by the GitHub action in gitops-example-app
          image: docker.io/phaneendrakotha/gitops-example-app:87eabc9c3d535c1796c2478513eb980ad3d20f81
          command:
            - python
            - -m
            - http.server
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred            # These are the creds we set up by hand earlier.
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: gitops-example-service-service
  namespace: gitops-example
spec:
  selector:
    app: gitops-example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
